
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Companies = lazy(() => import("./pages/Companies.tsx"));
const CompanyDetail = lazy(() => import("./pages/CompanyDetail.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/companies", element: <Companies />},
	{ path: "/company-detail", element: <CompanyDetail />},
	{ path: "/companydetail", element: <CompanyDetail />},

];
